/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// SubresourceClaimApplyConfiguration represents a declarative configuration of the SubresourceClaim type for use
// with apply.
//
// SubResourceClaim is a subresource/verb combination claimed as part of a [PermissionClaim].
type SubresourceClaimApplyConfiguration struct {
	// name is the name of the subresource.
	Name *string `json:"name,omitempty"`
	// verbs is a list of supported API operation types
	Verbs []string `json:"verbs,omitempty"`
}

// SubresourceClaimApplyConfiguration constructs a declarative configuration of the SubresourceClaim type for use with
// apply.
func SubresourceClaim() *SubresourceClaimApplyConfiguration {
	return &SubresourceClaimApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubresourceClaimApplyConfiguration) WithName(value string) *SubresourceClaimApplyConfiguration {
	b.Name = &value
	return b
}

// WithVerbs adds the given value to the Verbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verbs field.
func (b *SubresourceClaimApplyConfiguration) WithVerbs(values ...string) *SubresourceClaimApplyConfiguration {
	for i := range values {
		b.Verbs = append(b.Verbs, values[i])
	}
	return b
}
